export const disclaimer = `
/*
 * This file was generated by graphql-code-generator with the apollo-hooks-codegen plugin.
 * Any changes made to the file will be overwritten.
 */
`

export const imports = `
import { useMutation, useQuery, MutationHookOptions, QueryHookOptions, MutationResult, BaseMutationHookOptions, SubscriptionHookOptions, useSubscription } from 'react-apollo-hooks';
import gql from 'graphql-tag';

export declare type MutationHookFn<TData, TVariables> = (options?: BaseMutationHookOptions<TData, TVariables>) => Promise<{data: TData}>;
`

export const boilerplate = `
/*
 * Boilerplate
 */

type Nullable<T> = T | null
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>

`
